import React from 'react'
import type { Metadata } from 'next'
import { ReduxProvider } from '@/redux/provider'

import '@/styles/globals.css'
import '@/styles/fonts/pretendard.css'

import Footer from '@/layout/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="text-lato">
        <ReduxProvider>
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  )
}